frontal:
  build: frontal
  ports:
    - "80:80"
    - "443:443"
  links:
    - payara
payara:
  build: payara
  command: bin/asadmin start-domain -v
  links:
    - database-mysql
database-mysql:
  build: database-mysql
